print(True and True)
print(True and False)
print(False and True)
print(False and False)
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print(not True)
print(not False)
print(1<2 and 2>3)
print(1<2 and 1>3 or 2<5)
print(not(1<3 or 2>4 and 3>4))
